# Generated by Django 5.2.5 on 2025-08-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.ManyToManyField(blank=True, related_name='users', to='authentication.role'),
        ),
    ]
